global:
  pattern: xray

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  datacenter:
    cloudProvider: none
    storageClassName: "ocs-storagecluster-cephfs"
    region: ""
    clustername: ""
    domain: ""

  xraylab:
    namespace: "xraylab-1"

    s3:
      bucketSource: "xray-source"
      bucketBaseName: "xray-source"
      endpoint: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:80"
      s3ForcePathStyle: true
      signatureVersion: "s3v4"
      useSSL: false
      verifySSL: false
      region: "us-east-1"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
