global:
  pattern: xray

  datacenter:
    storageClassName: ocs-storagecluster-cephfs
    cloudProvider: onprem
    region: local
    clustername: 698d25073fd906765b7d10d0
    domain: 698d25073fd906765b7d10d0.am1.techzone.ibm.com

  xraylab:
    namespace: "xraylab-1"
    s3:
      bucketSource: "https://s3.amazonaws.com/validated-patterns-md-xray"
      bucketBaseName: "xray-source"
      endpoint: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
  clusterGroupChartVersion: 0.9.*
