global:
  pattern: xray   # was: xray  (optional change to silence the warning)

  datacenter:
    storageClassName: ocs-storagecluster-cephfs
    cloudProvider: onprem
    region: local
    clustername: <your-ocp-cluster-name>
    domain: 698a7c2d3930333074587e84.am1.techzone.ibm.com

  xraylab:
    namespace: "xraylab-1"
    s3:
      bucketSource: "xray-demo-saif-29f2e7e4-5d5a-4760-86fc-0f2a02e79bc4"
      bucketBaseName: "xray-source"
      endpoint: "https://s3-openshift-storage.apps.698a7c2d3930333074587e84.am1.techzone.ibm.com"

# ðŸ‘‡ NEW: required when using the slimmed common/ tree (no embedded Helm charts)
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
  clusterGroupChartVersion: 0.9.*
