global:
  pattern: xray   # was: xray  (optional change to silence the warning)

  datacenter:
    storageClassName: ocs-storagecluster-cephfs
    cloudProvider: onprem
    region: local
    clustername: <your-ocp-cluster-name>
    domain: 698a7c2d3930333074587e84.am1.techzone.ibm.com

  xraylab:
    namespace: "xraylab-1"
s3:
  bucketSource: "xray-source"
  bucketBaseName: "xray-source"
  endpoint: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
  clusterGroupChartVersion: 0.9.*
